/*
 Query para obtener el inventario de todos los almacenes
*/
SELECT
	cve_art, descr, lin_prod, fch_ultcom, fch_ultvta, exist AS total,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 1) AS A1,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 1 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC1,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 1 GROUP BY cve_art ORDER BY cve_art) AS CP1,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 1) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 1 GROUP BY cve_art ORDER BY cve_art) AS Sub1,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 2) AS A2,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 2 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC2,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 2 GROUP BY cve_art ORDER BY cve_art) AS CP2,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 2) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 2 GROUP BY cve_art ORDER BY cve_art) AS Sub2,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 3) AS A3,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 3 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC3,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 3 GROUP BY cve_art ORDER BY cve_art) AS CP3,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 3) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 3 GROUP BY cve_art ORDER BY cve_art) AS Sub3,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 4) AS A4,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 4 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC4,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 4 GROUP BY cve_art ORDER BY cve_art) AS CP4,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 4) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 4 GROUP BY cve_art ORDER BY cve_art) AS Sub4,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 5) AS A5,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 5 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC5,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 5 GROUP BY cve_art ORDER BY cve_art) AS CP5,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 5) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 5 GROUP BY cve_art ORDER BY cve_art) AS Sub5,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 6) AS A6,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 6 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC6,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 6 GROUP BY cve_art ORDER BY cve_art) AS CP6,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 6) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 6 GROUP BY cve_art ORDER BY cve_art) AS Sub6,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 7) AS A7,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 7 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC7,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 7 GROUP BY cve_art ORDER BY cve_art) AS CP7,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 7) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 7 GROUP BY cve_art ORDER BY cve_art) AS Sub7,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 8) AS A8,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 8 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC8,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 8 GROUP BY cve_art ORDER BY cve_art) AS CP8,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 8) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 8 GROUP BY cve_art ORDER BY cve_art) AS Sub8,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 9) AS A9,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 9 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC9,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 9 GROUP BY cve_art ORDER BY cve_art) AS CP9,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 9) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 9 GROUP BY cve_art ORDER BY cve_art) AS Sub9,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 10) AS A10,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 10 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC10,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 10 GROUP BY cve_art ORDER BY cve_art) AS CP10,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 10) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 10 GROUP BY cve_art ORDER BY cve_art) AS Sub10,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 11) AS A11,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 11 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC11,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 11 GROUP BY cve_art ORDER BY cve_art) AS CP11,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 11) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 11 GROUP BY cve_art ORDER BY cve_art) AS Sub11,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 12) AS A12,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 12 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC12,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 12 GROUP BY cve_art ORDER BY cve_art) AS CP12,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 12) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 12 GROUP BY cve_art ORDER BY cve_art) AS Sub12,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 13) AS A13,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 13 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC13,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 13 GROUP BY cve_art ORDER BY cve_art) AS CP13,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 13) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 13 GROUP BY cve_art ORDER BY cve_art) AS Sub13,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 14) AS A14,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 14 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC14,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 14 GROUP BY cve_art ORDER BY cve_art) AS CP14,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 14) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 14 GROUP BY cve_art ORDER BY cve_art) AS Sub14,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 15) AS A15,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 15 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC15,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 15 GROUP BY cve_art ORDER BY cve_art) AS CP15,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 15) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 15 GROUP BY cve_art ORDER BY cve_art) AS Sub15,

	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 16) AS A16,
	(SELECT costo FROM minve01 INNER JOIN(SELECT cve_art, MAX(minve01.num_mov) mov FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 16 GROUP BY cve_art) maximo on maximo.cve_art = minve01.cve_art AND maximo.mov = minve01.num_mov WHERE minve01.cve_art = inve01.cve_art ORDER BY minve01.cve_art) AS UC16,
	(SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 16 GROUP BY cve_art ORDER BY cve_art) AS CP16,
	(SELECT exist FROM mult01 WHERE mult01.cve_art = inve01.cve_art AND cve_alm = 15) * (SELECT SUM(cant * costo) / SUM(cant) FROM minve01 LEFT JOIN compc01 ON minve01.refer = compc01.cve_doc LEFT JOIN compr01 ON minve01.refer = compr01.cve_doc WHERE minve01.cve_art = inve01.cve_art AND (minve01.tipo_doc = 'c' OR minve01.tipo_doc = 'r') AND (compc01.status <> 'C' OR compr01.status <> 'C') AND minve01.almacen = 16 GROUP BY cve_art ORDER BY cve_art) AS Sub16
FROM inve01
WHERE inve01.status = 'A'
ORDER BY cve_art

