-- Eliminar productos con estatus baja
DELETE FROM INVE01
WHERE STATUS = 'B';

-- Limpiar datos
UPDATE INVE01
SET CVE_ART = TRIM(BOTH FROM REPLACE(REPLACE(REPLACE(REPLACE(CVE_ART, ASCII_CHAR(9), ''), ASCII_CHAR(160), ''), ASCII_CHAR(13), ''), ASCII_CHAR(10), ''));
    DESCR = TRIM(BOTH FROM REPLACE(REPLACE(REPLACE(REPLACE(DESCR, ASCII_CHAR(9), ''), ASCII_CHAR(160), ''), ASCII_CHAR(13), ''), ASCII_CHAR(10), ''));

-- Limpiar datos
UPDATE CLIE01
SET
    nombre = NULLIF(TRIM(REPLACE(REPLACE(nombre, ASCII_CHAR(13), ''), ASCII_CHAR(10), '')), ''),
    calle = NULLIF(TRIM(REPLACE(REPLACE(calle, ASCII_CHAR(13), ''), ASCII_CHAR(10), '')), ''),
    numext = NULLIF(TRIM(REPLACE(REPLACE(numext, ASCII_CHAR(13), ''), ASCII_CHAR(10), '')), ''),
    numint = NULLIF(TRIM(REPLACE(REPLACE(numint, ASCII_CHAR(13), ''), ASCII_CHAR(10), '')), ''),
    colonia = NULLIF(TRIM(REPLACE(REPLACE(colonia, ASCII_CHAR(13), ''), ASCII_CHAR(10), '')), '');
